# Generated by Django 5.2 on 2025-04-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailId', models.CharField(max_length=255, unique=True)),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('dueDate', models.DateField()),
                ('taskCompleted', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], max_length=10)),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManagement.userlogin')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('phoneNum', models.BigIntegerField()),
                ('companyName', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('joiningDate', models.DateField()),
                ('linkedIn', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TaskManagement.userlogin')),
            ],
        ),
    ]
